[tool.poetry]
name = "holochain-client"
version = "0.1.0"
description = "A Python client for the Holochain Conductor API"
authors = [
    "ThetaSinner <ThetaSinner@users.noreply.github.com>",
]
readme = "README.md"
license = "CAL 1.0"
keywords = ["holochain", "conductor-api"]
include = ["CHANGELOG.md"]

packages = [
    { include = "holochain_client" }
]

[tool.poetry.dependencies]
python = ">=3.14,<3.15"
msgpack = "^1.0.7"
websockets = "^16.0"
holochain-serialization = "^0.1.0"
cryptography = "^46.0.3"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.2"

[tool.poetry.group.dev.dependencies]
pytest-asyncio = "^1.3.0"
ruff = "^0.14.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
